// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Post struct {
	ID           uuid.UUID
	Slug         string
	Title        string
	Summary      string
	BodyMd       string
	BodyHtml     string
	SearchVector interface{}
	PublishedAt  *time.Time
	DeletedAt    *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type PostTag struct {
	PostID uuid.UUID
	TagID  int32
}

type Tag struct {
	ID        int32
	Slug      string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
