// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getPostBySlug = `-- name: GetPostBySlug :one
SELECT id, slug, title, summary, body_md, body_html, published_at, deleted_at, created_at, updated_at
FROM posts
WHERE slug = $1
    AND published_at <= CURRENT_TIMESTAMP
    AND deleted_at IS NULL
LIMIT 1
`

type GetPostBySlugRow struct {
	ID          uuid.UUID
	Slug        string
	Title       string
	Summary     string
	BodyMd      string
	BodyHtml    string
	PublishedAt *time.Time
	DeletedAt   *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// index: posts_slug_key (unique on slug).
func (q *Queries) GetPostBySlug(ctx context.Context, slug string) (GetPostBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPostBySlug, slug)
	var i GetPostBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Summary,
		&i.BodyMd,
		&i.BodyHtml,
		&i.PublishedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostIDBySlug = `-- name: GetPostIDBySlug :one
SELECT id
FROM posts
WHERE slug = $1
LIMIT 1
`

// index: posts_slug_key (unique on slug).
func (q *Queries) GetPostIDBySlug(ctx context.Context, slug string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getPostIDBySlug, slug)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listPosts = `-- name: ListPosts :many
SELECT id, slug, title, published_at
FROM posts
WHERE published_at <= CURRENT_TIMESTAMP
  AND deleted_at IS NULL
  AND (published_at, id) < (
    coalesce($1::timestamptz, 'infinity'),
    coalesce($2::uuid, 'ffffffff-ffff-ffff-ffff-ffffffffffff')
  )
ORDER BY published_at DESC, id DESC
LIMIT $3
`

type ListPostsParams struct {
	AfterPublishedAt *time.Time
	AfterID          *uuid.UUID
	PageSize         int32
}

type ListPostsRow struct {
	ID          uuid.UUID
	Slug        string
	Title       string
	PublishedAt *time.Time
}

// index: posts_pagination_idx (published_at DESC, id DESC) WHERE published_at IS NOT NULL AND deleted_at IS NULL.
func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]ListPostsRow, error) {
	rows, err := q.db.Query(ctx, listPosts, arg.AfterPublishedAt, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsRow
	for rows.Next() {
		var i ListPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePost = `-- name: SoftDeletePost :one
UPDATE posts
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id
`

// index: posts_pkey (id).
func (q *Queries) SoftDeletePost(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeletePost, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const upsertPost = `-- name: UpsertPost :one
INSERT INTO posts (slug, title, summary, body_md, body_html, published_at)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
ON CONFLICT (slug) DO UPDATE
SET
  title = EXCLUDED.title,
  summary = EXCLUDED.summary,
  body_md = EXCLUDED.body_md,
  body_html = EXCLUDED.body_html,
  published_at = EXCLUDED.published_at,
  deleted_at = NULL,
  updated_at = CURRENT_TIMESTAMP
WHERE (
    (posts.title, posts.summary, posts.body_md, posts.body_html, posts.published_at)
    IS DISTINCT FROM
    (EXCLUDED.title, EXCLUDED.summary, EXCLUDED.body_md, EXCLUDED.body_html, EXCLUDED.published_at)
  )
  OR posts.deleted_at IS NOT NULL
RETURNING id, (old.id IS NULL)::boolean AS created
`

type UpsertPostParams struct {
	Slug        string
	Title       string
	Summary     string
	BodyMd      string
	BodyHtml    string
	PublishedAt *time.Time
}

type UpsertPostRow struct {
	ID      uuid.UUID
	Created bool
}

// index: posts_slug_key (unique on slug).
func (q *Queries) UpsertPost(ctx context.Context, arg UpsertPostParams) (UpsertPostRow, error) {
	row := q.db.QueryRow(ctx, upsertPost,
		arg.Slug,
		arg.Title,
		arg.Summary,
		arg.BodyMd,
		arg.BodyHtml,
		arg.PublishedAt,
	)
	var i UpsertPostRow
	err := row.Scan(&i.ID, &i.Created)
	return i, err
}
