// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteTagsForPostExcept = `-- name: DeleteTagsForPostExcept :execrows
DELETE FROM post_tags
WHERE post_id = $1
  AND NOT (tag_id = ANY(coalesce($2::int[], '{}')))
`

type DeleteTagsForPostExceptParams struct {
	PostID uuid.UUID
	TagIds []int32
}

// index: post_tags_pkey (post_id, tag_id), leading column.
// A NULL array would make NOT (tag_id = ANY(NULL)) NULL and delete nothing,
// so treat it as empty: no tags means remove every link.
func (q *Queries) DeleteTagsForPostExcept(ctx context.Context, arg DeleteTagsForPostExceptParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTagsForPostExcept, arg.PostID, arg.TagIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTagsBySlugs = `-- name: GetTagsBySlugs :many
SELECT id, slug, name
FROM tags
WHERE slug = ANY($1::text[])
ORDER BY slug ASC
`

type GetTagsBySlugsRow struct {
	ID   int32
	Slug string
	Name string
}

// index: tags_slug_key (unique on slug), one probe per slug in the array.
func (q *Queries) GetTagsBySlugs(ctx context.Context, slugs []string) ([]GetTagsBySlugsRow, error) {
	rows, err := q.db.Query(ctx, getTagsBySlugs, slugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTagsBySlugsRow
	for rows.Next() {
		var i GetTagsBySlugsRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByTag = `-- name: ListPostsByTag :many
SELECT p.id, p.slug, p.title, p.published_at
FROM posts p
JOIN post_tags pt ON p.id = pt.post_id
WHERE pt.tag_id = $1
  AND p.published_at <= CURRENT_TIMESTAMP
  AND p.deleted_at IS NULL
  AND (p.published_at, p.id) < (
    coalesce($2::timestamptz, 'infinity'),
    coalesce($3::uuid, 'ffffffff-ffff-ffff-ffff-ffffffffffff')
  )
ORDER BY p.published_at DESC, p.id DESC
LIMIT $4
`

type ListPostsByTagParams struct {
	TagID            int32
	AfterPublishedAt *time.Time
	AfterID          *uuid.UUID
	PageSize         int32
}

type ListPostsByTagRow struct {
	ID          uuid.UUID
	Slug        string
	Title       string
	PublishedAt *time.Time
}

// index: posts_pagination_idx (published_at DESC, id DESC) WHERE published_at IS NOT NULL AND deleted_at IS NULL.
func (q *Queries) ListPostsByTag(ctx context.Context, arg ListPostsByTagParams) ([]ListPostsByTagRow, error) {
	rows, err := q.db.Query(ctx, listPostsByTag,
		arg.TagID,
		arg.AfterPublishedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsByTagRow
	for rows.Next() {
		var i ListPostsByTagRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForPost = `-- name: ListTagsForPost :many
SELECT t.id, t.slug, t.name
FROM tags t
JOIN post_tags pt ON t.id = pt.tag_id
WHERE pt.post_id = $1
ORDER BY t.slug ASC
`

type ListTagsForPostRow struct {
	ID   int32
	Slug string
	Name string
}

// index: post_tags_pkey (post_id, tag_id) finds the post's rows by its leading column; tags_pkey for the join.
// ORDER BY t.slug sorts in memory, fine for a handful of tags per post.
func (q *Queries) ListTagsForPost(ctx context.Context, postID uuid.UUID) ([]ListTagsForPostRow, error) {
	rows, err := q.db.Query(ctx, listTagsForPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsForPostRow
	for rows.Next() {
		var i ListTagsForPostRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTagsForPost = `-- name: SetTagsForPost :execrows
INSERT INTO post_tags (post_id, tag_id)
SELECT $1, UNNEST($2::int[])
ON CONFLICT (post_id, tag_id) DO NOTHING
`

type SetTagsForPostParams struct {
	PostID uuid.UUID
	TagIds []int32
}

// index: post_tags_pkey (post_id, tag_id).
func (q *Queries) SetTagsForPost(ctx context.Context, arg SetTagsForPostParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTagsForPost, arg.PostID, arg.TagIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertTag = `-- name: UpsertTag :execrows
INSERT INTO tags (slug, name)
VALUES ($1, $2)
ON CONFLICT (slug) DO NOTHING
`

type UpsertTagParams struct {
	Slug string
	Name string
}

// index: tags_slug_key (unique on slug).
func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertTag, arg.Slug, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
